README.md
Add _hydrpowerlib_, _oemof_ and _Open Energy Family_
Great work and happy to contribute!
=> Add projects to list

README.md
Added a Datasets of _Ecosystems Section_ and filled with climate datasets.
It was a pleasure to contribute!
Probably, it would be a good idea for future to add other kinds of environmental data (for example, forest coverage data)?
=> Add Datasets of Ecosystems

README.md
The [karrot project](https://karrot.world/#/) reduces the consumption of resources in the field of nutrition.
=> add yunity/karrot-frontend

README.md
Our backend code can be cloned on github https://github.com/gridsingularity/d3a 
We have an open, accessible community slack space: https://gsycommunity.slack.com/ where everybody is invited to contribute and ask questions, may it be regarding the topic of energy exchanges or questions regarding the code or feature requests. We also accept feature request via github (see our contribution guidelines: https://github.com/gridsingularity/d3a/blob/master/CONTRIBUTING.md )
We have an up-to-date wiki for the general concepts as well as for the backend code: https://gridsingularity.github.io/d3a/d3a-documentation/
Our backend code is open source under GLPv3.0 license https://github.com/gridsingularity/d3a/blob/master/LICENSE 
Our project is awesome, because we enable energy consumers and …
=> Added GridSingularityD3A

README.md
=> Weekly Maintainer Meeting of protontypes

README.md
Projects found in the pangeo community
=> Supplement to Weekly Meeting

README.md
=> Weekly Merging and Maintenance

.github/workflows/tweet.yml, README.md, docs/COMMUNITIES.md, docs/EDUCATION.md
* Discussion about Twitter Bot
* Some new Projects
=> Weekly Maintainer Meeting

README.md
First contribution, I hope you like it.
=> An Open Data Initiative designed to help enable rapid carbon abatement for cities worldwide. https://www.transitionproject.org/ @ClimateView

.github/workflows/tweet.yml, README.md, docs/EDUCATION.md, mkdocs.yml
Moved educational links to a new file (docs/EDUCATIONAL.md).
Checked proposed links.
=> Weekly review meeting.

README.md, docs/index.md
Merging changes made to main directly into agri
=> solved most toc issues

README.md
Several typos and grammar corrections. Also changes in the first paragraph's quote.
=> Typos and grammar corrections

README.md
Basic spell- and grammar-check 👍
=> K kulma patch 1

README.md
Add CapacityExpansion.jl in Energy System Assessment - Modeling. 
The package allows for an expandable modeling of generation and transmission capacity expansion planning for future energy systems. It provides both simple-to-use code and sample datasets. 
The package complies with the guideline because it is open source both in its software and provides some sample datasets, has been published in the journal of open source software, has been contributed to by authors beyond the core authors (see issues/PRs), is structured so that it can be reused and extended (including that we provide comments and documentation).
=> Add CapacityExpansion.jl

README.md
Add TimeSeriesClustering.jl package to Energy System Assessment - Optimization. 
The package supports time series aggregation for energy systems time series datasets. This allows for large-scale long-term planning of sustainable energy systems.
The package complies with the guideline because it is open source both in its software and provides some sample datasets, has been published in the journal of open source software, has been contributed to by authors beyond the core authors (see issues/PRs), is structured so that it can be reused and extended (including that we provide comments and documentation).
=> Add TimeSeriesClustering

README.md
[Recyclebot](https://www.appropedia.org/Recyclebot) is an open source waste plastic extruder that creates 3-D printer filament from waste plastic and natural polymers.
The designs and bill of materials to build a Recyclebot are 100% open source and viewable on [Appropedia](https://www.appropedia.org/Recyclebot). Recyclebot is actively under development at [Michigan Tech's Open Sustainability Laboratory](https://www.appropedia.org/Category:MOST).
=> Add Recyclebot

CONTRIBUTING.md
"indicator" is singular, followed by "is."
=> Fix typo, and match singular noun to verb

.github/workflows/check_links.yml, README.md
Closes #76.
Summary:
- I've added a new GitHub Action workflow to check links (`check_links.yml`). Feel free to change the workflow file name/description/schedule. I've also used the Ruby gem method, but you can change it to the Docker method if you wish.
- Fixed one broken link.
- I noticed that two projects in the list have been archived: [Bloom](https://github.com/tmrowco/bloom-contrib) and [Apache Open Climate Workbench](https://github.com/apache/attic-climate).
- There was also a duplicate entry (PowerGAMA), which has been removed.
- I've added two projects to the link checker's whitelist: `lcacommons.gov` and `ecostress.jpl.nasa.gov`. This is to prevent the action from failing due to certificate issues.
Let me know if there's anything else I can do.
=> Add workflow to validate links in README.md

README.md
I'm adding the BikeshareClient project to the list since a link to the GBFS (General Bikeshare Feed Specification) already is present. The client makes it possible to integrate with GBFS systems via C# and dotnet, to make applications or dashboards showing status of your local GBFS bikeshare system.
=> Added BikeshareClient to list of Mobility and Transportation

README.md
I propose adding [Meteostat Python](https://github.com/meteostat/meteostat-python) to the list of weather data sources.
=> Add Meteostat data source

README.md
@rhammond2 I think your WOMBAT software is very relevant to this list. What do you think?
Here are the guidelines for including a project:
=> Add link to WOMBAT

README.md
[[GHEtool]](https://github.com/wouterpeere/GHEtool)
GHEtool is an open-source python package centered around the sizing of borefields. It is developed for both researchers and practitioners. Since borefields play an important role in the energy transition and fifth generation district heating, but they are expensive to construct, sizing them correctly is very important. This package offers all the tools and functions in order to do so.
Furthermore, GHEtool also comes with a graphical user interface [GUI](https://www.mech.kuleuven.be/en/tme/research/thermal_systems/tools/ghetool) for ease of use.
**The community behind OpenSustain.tech offers free marketing and …
=> Add GHEtool

README.md
https://github.com/open-ideas/IDEAS
IDEAS is an open source Modelica library that has been maintained and developed at the university of Leuven for over 10 years. It has been used in over 50 research papers. Its goal is to allow detailed and multi-disciplinary simulation and optimisation of building envelope models, including their Heating, Ventilation and air conditioning. Research topics relate to minimising the energy footprint of buildings.
**The community behind OpenSustain.tech offers free marketing and consulting for open source projects added to the list. If you are interested just tick here:**
=> added IDEAS to the list

README.md
[BOPTEST](https://github.com/ibpsa/project1-boptest)
[BOPTEST-Gym](https://github.com/ibpsa/project1-boptest-gym)
The BOPTEST project is an innovative, open, and international initiative aiming to throw light on best practices for building energy management. It provides reliable building emulators, standardized scenarios, and a run-time environment to facilitate the assessment and comparison of control algorithms in buildings. The number of forks and issues shows that there are people other than the main developers using the repositories already. Also, extensive documentation exists for BOPTEST in [this link](https://ibpsa.github.io/project1-boptest/docs-userguide/inde …
=> Add BOPTEST and BOPTEST-Gym to the list.

README.md
**Insert URLs to the project(s) here:** 
- https://git.tu-berlin.de/genesysmod/genesys-mod-public
- https://github.com/fineprint-global
- https://github.com/konstantinstadler/pymrio
- https://github.com/CMLPlatform/ramascene
- https://github.com/CMLPlatform/CircuMAT
- https://github.com/byrd-polar/fluid-earth
- https://github.com/TNO/EXIOMOD-open
Active projects widely used by the community.
**The community behind OpenSustain.tech offers free marketing and consulting for open source projects added to the list. If you are interested just tick here:**
=> Add projects and rename EF category to IE

README.md
- https://github.com/fvaleye/tracarbon
Tracarbon is a Python library that automatically tracks the energy consumption of a device and calculates the carbon emission by using its location and its context.
**The community behind OpenSustain.tech offers free marketing and consulting for open source projects added to the list. If you are interested just tick here:**
=> Add Tracarbon in Carbon Intensity and Accounting section

README.md
- https://github.com/pypsa-meets-earth/pypsa-earth
- We recently rebranded our activities, hence, corrections are necessary. We started 2021 as the **PyPSA-meets-Africa initiative**, where we host multiple projects on open data, open source tools and an open community. Early this year we rebranded the initiative to **[PyPSA-meets-Earth initiative](https://pypsa-meets-earth.github.io/)** since the scope expanded. The correct term for the energy system model hosted by the initiative is now PyPSA-Earth. 
**The community behind OpenSustain.tech offers free marketing and consulting for open-source projects added to the list. If you are interested just tick here:**
=> pypsa-earth fix

README.md
Open source repository of energy datasets
https://energydata.info/
ENERGYDATA.INFO has been developed as a public good available to governments, development organizations, private sector, non-governmental organizations, academia, civil society and individuals to share data and analytics that can help achieving the UN’s SDG 7 of ensuring access to affordable, reliable, sustainable, and modern energy for all.
The World Bank and the International Finance Corporation, collectively the World Bank Group (WBG) strives to enhance public access to and use of data that can support development impact. ENERGYDATA.INFO is designed according to open data and open source standards …
=> Adding EnergyData.info

learning.md
[ Your URLs ]
[ Your Text ]
**The community behind OpenSustain.tech offers free marketing and consulting for open source projects added to the list. If you are interested just tick here:**
=> updated repo link of ystems eng for energy efficiency

README.md
https://github.com/aditya-grover/climate-learn by @aditya-grover
A Python library for accessing state-of-the-art climate data and machine learning models in a standardized, straightforward way.
=> Add ClimateLearn library

README.md
[[ Your URLs ]](https://github.com/microsoft/CameraTraps/)
MegaDetector is an object detector that's primarily used to separate wildlife camera trap images that are empty/animal/person/vehicle.
=> Added MegaDetector to "biosphere" list

README.md
EVerest is actively in development. Updated the description to better meet the real status of the project.
** URLs to the project:**      
[ [EVerest](https://github.com/EVerest/everest) ]
**Further info:**     
[ EVerest has already been listed but has to be updated with more information ]
=> Updated description of EVerest project

README.md
Hi! Found this collection and suggest adding it. I am not affiliated.
URLs to the project:
https://energy.acm.org/resources/
According to their site, a curated collection of publicly available datasets, models, and software that The ACM Special Interest Group on Energy Systems and Informatics (SIGEnergy) finds to be useful for researchers and professionals who study energy systems and informatics.
More information can be found via the link I have provided.
=> Adding Energy Systems and Informatics collection of resources to Curated Lists

README.md
http://ayce.earth
Open source LCA framework to calculate CO₂ emissions of food.
=> Add Eaternity Ayce

README.md
[pyNuMAD](https://github.com/sandialabs/pyNuMAD)
pyNuMAD is a software project dedicated to the creation and analysis of 3D models of blades for wind turbines. It is used to carry out experiments regarding the structural design of blades. 
Although this particular repository is very new, the core of the software has been around for over a decade. The last "version" of the software, written in matlab, can be found at https://github.com/sandialabs/NuMAD. pyNuMAD is really just a translation/redesign of this other code.
=> Adding pyNuMAD to software list

.github/workflows/main.yml, README.md
* Moved Radiative Transfer and Meteorological Observation and Forecast to the Atmosphere field.
* Split Climate fields
* Cleanup of projects that are not correctly sorted 
* New headline that better represents the goals of the projects
=> Split fields climate

README.md
https://github.com/firelab/windninja
A diagnostic wind model developed for use in wildland fire modeling.
Note: The project has a customized open source license.
=> Add WindNinja

README.md
https://github.com/quant-aq/py-smps
A Python data analysis library built for analyzing size-resolved aerosol data from a variety of aerosol sizing instruments.
=> Add py-smps

README.md
https://github.com/AugustinMortier/a-profiles
A-Profiles is a python library dedicated to the analysis of atmospheric profilers measurements.
=> Add A-Profiles

README.md
https://github.com/Unidata/gempak
Analysis and product generation for meteorological data.
=> Add GEMPAK

README.md
https://github.com/anikfal/PostWRF
Visualization and postprocessing of the WRF and ERA5 data
=> Add PostWRF

README.md
https://github.com/google-deepmind/graphcast
https://arxiv.org/abs/2212.12794
Predicting world weather.
=> add graphcast

README.md
https://github.com/cpmodel/FTT_StandAlone
Integrated assessment model with a realistic treatment of technology diffusion.
=> Add Future Technology Transformation

README.md
https://github.com/mila-iqia/climate-cooperation-competition
AI for Global Climate Cooperation: Modeling Global Climate Negotiations, Agreements, and Long-Term Cooperation in RICE-N. ai4climatecoop.org
=> Add climate-cooperation-competition

README.md
https://github.com/uncefact/project-crm
Critical raw materials traceability & transparency project
=> Add UN/CEFACT CRM

README.md
https://github.com/scikit-maad/scikit-maad
Estimating animal acoustic diversity in tropical environments using unsupervised multiresolution analysis.
In this project the README also does not provide keywords / relations to sustainability relevant topics but the referenced paper does at the top.
=> Add scikit-maad

README.md
As recommended by @juansulloa in https://github.com/protontypes/open-sustainable-technology/commit/cfc51cc86d9f487a7d1d42946d87125796758e87
=> Update description of scikit-maad

README.md
https://github.com/martinber/noaa-apt
Receive and decode images from weather satellites via radio signals.
@andrew This project is considered sustainable because it enables to recive, without internet connection, weather satellite data essential for many sustainability application.
=> Add noaa-apt

README.md
https://github.com/CliMA/CalibrateEDMF.jl
A package to calibrate atmospheric turbulence and convection parameterizations using gradient-free ensemble Kalman methods
=> Add CalibrateEDMF.jl

README.md
https://github.com/stevage/OpenTrees
A data visualisation of millions of publicly maintained trees around the world.
=> Add OpenTrees.org

README.md
https://github.com/openclimatefix/graph_weather
Data-driven approach for forecasting global weather using graph neural network.
=> Add Graph Weather

README.md
https://github.com/peterkuma/ccplot
Command-line application for visualizing data from CloudSat and CALIPSO satellites
=> Add ccplot

README.md
https://github.com/changliao1025/pyflowline
A mesh independent river network generator for hydrologic models
=> Add PyFlowline

README.md
https://github.com/ternaustralia/ausplotsR
Directly access plot-based data on vegetation and soils across Australia, with simple function calls to extract the data and merge them into species occurrence matrices for analysis or to calculate things like basal area and fractional cover.
=> Add ausplotsR

README.md
https://github.com/repolicy/csp-guru
An open-source database of concentrating solar power plants of the world for energy modellers and analysts.
=> Add CSP.guru

README.md
[[ Your URLs ]](https://github.com/MIT-LAE/APCEMM)
Aircraft Plume Chemistry, Emissions, and Microphysics Model
=> Add APCEMM

README.md
https://github.com/pietern/goestools
Tools to work with signals and files from GOES satellites
=> Add goestools

README.md
https://github.com/meirim-org/meirim
Meirim is an open-source smart city application that facilitates transparency in urban planning.
The sustainability aspect it a little bit hidden in the website: https://meirim.org/trees/
> In order to cut a mature tree in Israel - in public or private territory - a resection license must be issued. From the date of publication of the license, the public has 14 days [Submit a appeal](https://meirim.org/docs/%D7%9E%D7%93%D7%A8%D7%99%D7%9A%20%D7%9C%D7%94%D7%92%D7%A9%D7%AA%20%D7%A2%D7%A8%D7%A8%20%D7%A2%D7%9C%20%D7%9B%D7%A8%D7%99%D7%AA%D7%AA%20%D7%A2%D7%A5.pdf).
The website showes where tree cutting in Israel is happening.
=> Add Meirim

README.md
https://github.com/3DStreet/3dstreet
Creates 3D visualizations of your 2D [Streetmix.net](https://streetmix.net/) streets using A-Frame and WebXR
=> Add 3Dstreet

README.md
https://github.com/nsidc/earthaccess
A python library to search, download or stream NASA Earth science data with just a few lines of code.
=> Add earthaccess

README.md
https://github.com/josuemtzmo/trackeddy
Used to investigate trends of eddy kinetic energy in the ocean using satellite sea surface height anomaly.
=> Add TrackEddy

README.md
https://github.com/transition-zero/feo-client
Crafted for energy systems modellers seeking access to data for nodes, assets, technologies, as well as the data supporting models and scenarios published by TransitionZero.
=> Add feo-client

README.md
https://github.com/MeteoSwiss/ldcast
A precipitation nowcasting model based on a latent diffusion model.
=> Add LDCast

README.md
https://github.com/TEOS-10/GSW-Python
This Python implementation of the Thermodynamic Equation of Seawater 2010.
=> Add GSW-Python

docs/index.md
https://solarnetwork.net
https://github.com/SolarNetwork/solarnetwork/wiki
https://github.com/SolarNetwork/solarnetwork-node
Flexible platform for the monitoring and control of energy assets, meters, sensors, weather stations, EV chargers, market pricing, load optimization, and more.
=> Add SolarNetwork project

README.md
https://github.com/CharlesGillanders/homeassistant-alphaESS
Monitor your energy generation, storage, and usage data using the official Open API from Alpha ESS.
=> Add homeassistant-alphaESS

README.md
https://github.com/KartoffelToby/better_thermostat
This custom component for Home Assistant will add crucial features to your climate-controlling Thermostatic Radiator Valves to save you the work of creating automations to make it smart.
This project is considered sustainable because energy usage in heating is massive. Smart hearting has a huge potential to reduce this consumption: https://ec.europa.eu/eurostat/statistics-explained/index.php?title=Energy_consumption_in_households
=> Add Better Thermostat

README.md
https://github.com/BIG-MAP/big-map-registry
The Battery Interface Genome Materials Acceleration Platform is promoting accelerated discovery of novel battery materials.
=> Add BIG-MAP

README.md
https://github.com/ec0lint/ec0lint-style
A static code analysis tool that provides users with hints on how to reduce the carbon footprint of their websites during the development process.
=> Add ec0lint

README.md
https://github.com/aodn/aodn-portal
The gateway to Australian marine and climate science data.
=> Add AODN Porta

README.md
https://github.com/ropensci/worrms
A R client for the World Register of Marine Species.
=> Add worrms

README.md
https://github.com/C4IROcean/odp-sdk-python
Download queried ocean data easily and efficiently into data frames, for easy exploring and further processing in your data science project.
=> Add odp_sdk

README.md
https://github.com/PlanktonTeam/planktonr
R package that facilitates the download, analysis and visualisation of phytoplankton and zooplankton data.
=> Add planktonr

education.md
https://github.com/UCL-EO/geog0133
The role of vegetation in the carbon cycle and the wider climate system.
=> Add Terrestrial Carbon: modelling and monitoring

README.md
https://github.com/w3c/sustyweb
The draft specification for our Web Sustainability Guidelines and any supplementary documentation, including our introduction to Web Sustainability.
=> Add Web Sustainability Guidelines

README.md
https://github.com/openearth/sealevel
Tools and applications used to monitor sea-level rise.
=> Add Sea-level monitor

README.md
https://github.com/ImperialCollegeLondon/pyrealm
A toolbox implementing some key models for estimating plant productivity, growth and demography in Python 3.
=> Add pyrealm

README.md
https://github.com/flauschtrud/broccoli
A free eco-friendly recipe app for building your recipe collection, distraction free cooking and seasonal ingredients.
=> Add Broccoli

README.md
https://github.com/dalmo1991/superflexPy
An open-source framework written in Python for constructing flexible, conceptual, distributed hydrological models.
=> Add SuperflexPy

README.md
https://github.com/metoppv/improver
A library of algorithms for meteorological post-processing and verification.
=> Add IMPROVER

README.md
https://github.com/VeinsOfTheEarth/rabpro
Delineating watershed basins and computing attribute statistics using Google Earth Engine.
=> Add rabpro

education.md
https://github.com/blutjens/climate-emulator-tutorial
A tutorial for getting started with machine learning for climate modeling
=> Add climate-emulator-tutorial

README.md
https://github.com/PCMDI/pcmdi_metrics
Open-source Python package for Systematic Evaluation of Climate and Earth System Models
=> Add PCMDI Metrics Package

README.md
https://github.com/kitzeslab/opensoundscape
A free and open source Python utility library analyzing bioacoustic data.
=> Add OpenSoundscape

education.md
https://github.com/weecology/forecasting-course
This is a course on how ecological systems change through time and how to forecast how they will change in the future.
=> Add Ecological Forecasting & Dynamics Course

README.md
https://github.com/EricMarcon/entropart
An R package that provides functions to calculate alpha, beta and gamma diversity of communities, including phylogenetic and functional diversity.
=> Add entropart

README.md
https://github.com/ICESat2-SlideRule/sliderule
Process Earth science datasets in the cloud through REST API calls to SlideRule web services.
=> Add SlideRule Earth

README.md
https://github.com/eurodatacube/eodash
Combines the resources, technical knowledge and expertise of three partner agencies ESA, JAXA, and NASA to strengthen our global understanding of global environmental changes and other societal challenges impacting our planet.
=> Add eodash

README.md
https://github.com/lter/lterdatasampler
Provide the scientific community, policy makers, and society with the knowledge and predictive understanding necessary to conserve, protect, and manage the nation’s ecosystems, their biodiversity, and the services they provide.
=> Add lterdatasampler

README.md
https://github.com/protontypes/climate-triage
Discover a meaningful way to contribute to open source projects focused on climate technology and sustainability.
=> Add ClimateTriage

README.md
https://github.com/consbio/seedlot-selection-tool
A GIS mapping program designed to help forest managers match seedlots with planting sites based on climatic information.
=> Add Seedlot Selection Tool

README.md
https://github.com/birdflow-science/BirdFlowR
Predict changes in bird distributions and generate synthetic migration routes.
=> Add BirdFlowR

README.md
https://github.com/aalto-electric-drives/motulator
Simulation models for an induction motor, a synchronous reluctance motor, and a permanent-magnet synchronous motor.
=> Add motulator

README.md
https://github.com/rebipp/ppi
Plant-Pollinator Interactions Vocabulary
=> Add Plant-Pollinator Interactions Vocabulary

CONTRIBUTING.md
The mission statements says capture what has a bad tone. Gather decribes more the community aspect of what we are doing.
=> Switch capture to gather

README.md
https://github.com/carlos-alberto-silva/ForestGapR
An R Package for Airborne Laser Scanning-derived Tropical Forest Gaps Analysis.
=> Add ForestGapR

README.md
https://github.com/evetion/SpaceLiDAR.jl
A Julia toolbox for ICESat, ICESat-2 and GEDI data. Quickly search, download, and load filtered point data with relevant attributes from the .h5 granules of each data product.
Note: The data from ICESat, ICESat-2 and GEDI are of great importance for the geosciences and other environmentally relevant sciences.
=> Add SpaceLiDAR

README.md
https://github.com/byuflowlab/FLOWFarm.jl
Wind farm simulation tool for gradient-based optimization.
=> Add FLOWFarm.jl

education.md
https://github.com/wekeo/wekeo4atmosphere
With the help of cases studies about the monitoring of wildfires and air quality, Copernicus atmosphere data from the Copernicus Programme are introduced.
=> Add WEkEO4Atmosphere

README.md
https://github.com/OceanNetworksCanada/api-python-client
Provides easy access to Ocean Networks Canada data in Python
=> Add Ocean Networks Canada

README.md
https://github.com/opengeos/leafmap
A Python package for interactive mapping and geospatial analysis with minimal coding in a Jupyter environment.
=> Add leafmap

README.md
https://github.com/pydata/xarray
=> Add xarray

README.md
https://github.com/j-c-cook/ghedt
=> Add Ground Heat Exchanger Design Tool

README.md
https://github.com/sharppy/SHARPpy
=> Add SHARPpy

README.md
https://github.com/dynawo/dynawo
=> Add Dynaωo

README.md
https://github.com/mitrefireline/simfire
=> Add SimFire

README.md
https://github.com/PyPSA/pypsa-usa
=> Add PyPSA-USA

README.md
https://github.com/PyPSA/247-cfe
=> Add 24/7 CFE

README.md
This PR is for removing projects that are not open source that can be found here:
https://gist.github.com/andrew/c21b243c555745f94ec686a276728436
Relates to #306 
Progress:
Done! I kept some Awesome lists which had no licence but were well maintained. Really shocking how many open source project have open in their name but are not open source per definiton.
=> Remove projects not open source

education.md
https://github.com/vboussange/WSLJuliaWorkshop2023
=> Add WSL Julia Workshop 2023

README.md
https://github.com/USEPA/StreamCat
=> Add StreamCat

README.md
https://github.com/dbca-wa/FireHistory
=> Add FireHistory

README.md
https://github.com/EDIorg/ecocomDP
=> Add ecocomDP

README.md
https://github.com/NIWAFisheriesModelling/CASAL2
=> Add CASAL2

README.md
https://github.com/smnorris/bcfishobs
=> Add bcfishobs

README.md
https://github.com/danlwarren/ENMTools
=> Add ENMTools

README.md
https://github.com/sertit/eoreader
=> Add EOReader

README.md
https://github.com/NFrancart/doughnut-biotool
=> Add Doughnut-biotool and move eu_cbm_hat

README.md
https://github.com/ropensci/CoordinateCleaner
=> Add CoordinateCleaner

README.md
https://github.com/ropensci/rnassqs
=> Add rnassqs

README.md
https://github.com/the-clothing-loop/website
=> Add The Clothing Loop

education.md
https://github.com/oemof/heat-pump-tutorial
=> Add heatpump_workshop

README.md
https://github.com/btschwertfeger/python-cmethods
=> Add python-cmethods

README.md
https://github.com/EnergySystemsModellingLab/MUSE_OS
I had to dig really deep into the documentation to find a oneliner for the project:
> MUSE is an open source agent-based modelling environment that can be used to simulate change in an energy system over time.
=> Add MUSE_OS

README.md
https://github.com/TulipaEnergy/TulipaEnergyModel.jl
=> Add TulipaEnergyModel.jl

README.md
https://github.com/powsybl/pypowsybl
=> Add PyPowSyBl

README.md
https://github.com/Qepanna/goFlux
=> Add goFlux

README.md
https://github.com/matplotlib/cmocean
=> Add cmocean

README.md
https://github.com/RMI-PACTA/r2dii.match
=> Add r2dii.match

education.md
https://github.com/JeremyDForsythe/icecream-tutorials
=> Add ECOSTRESS Tutorial

README.md
https://github.com/jhnienhuis/GlobalDeltaChange
=> Add GlobalDeltaChange

README.md
https://github.com/pommes-public/pommesdispatch
=> Add pommesdispatch

README.md
https://github.com/cat-cfs/libcbm_py
Further Links:
https://natural-resources.canada.ca/climate-change/climate-change-impacts-forests/carbon-accounting/carbon-budget-model/13107
=> Add CBM-CFS3

README.md
https://github.com/mrke/NicheMapR
=> Add NicheMapR

education.md
https://github.com/CWWhitney/Decision_Analysis_Course
=> Add Decision Analysis and Forecasting for Agricultural Development

README.md
https://github.com/trenchproject/TrenchR
=> Add TrenchR

education.md
https://github.com/xarray-contrib/xarray-tutorial
=> Add Xarray Tutorial

README.md
https://github.com/WildEyeConservation/TrapTagger
=> Add TrapTagger

README.md
https://github.com/geco-bern/rsofun
=> Add rsofun

README.md
https://github.com/maureentsakiris/coastwards
=> Add Coastwards

README.md
https://github.com/Deltares/D-EcoImpact
=> Add D-EcoImpact

README.md
https://github.com/Accenture/EcoSonar
=> Add EcoSonar

education.md
https://github.com/nicholasjclark/physalia-forecasting-course
=> Add Ecological forecasting with R

README.md
https://github.com/Molina-Valero/FORTLS
=> Add FORTLS

README.md
=> add RICorDE and FloodDownscaler

README.md
https://github.com/cryologger/glacier-velocity-tracker
=> Add Glacier Velocity Tracker

README.md
https://github.com/cryologger/ice-tracking-beacon
=> Add Iceberg Tracking Beacon

README.md
https://github.com/ecmwf-ifs/dwarf-p-cloudsc
=> Add dwarf-p-cloudsc

README.md
https://github.com/Vizzuality/half-earth-v3
=> Add Half Earth

README.md
https://github.com/openEDI/open-data-access-tools
=> Add Open Data Access Tools

README.md
https://github.com/naturalsolutions/ecoSecrets
=> Add ecoSecrets

README.md
https://github.com/respec/HSPsquared
=> Add HSPsquared

README.md
https://github.com/emlab-ucsb/oceandatr
=> Add oceandatr

README.md
https://github.com/BirdLifeInternational/track2kba
=> Add track2KBA

README.md
https://github.com/bionomia/bionomia
=> Add Bionomia

README.md
VeganCheck had to change its name due to legal reasons. This should also be reflected in all linking pages/repos.
You can link to us now as Veganify @ veganify.app
Thank you!
https://veganify.app
=> Update Veganify Link

README.md
https://github.com/logan-berner/LandsatTS
=> Add LandsatTS

README.md
https://github.com/biocro/biocro
=> Add BioCro

README.md
https://github.com/ForModLabUHel/Rprebasso
=> Add Rprebasso

README.md
https://github.com/iiasa/ibis.iSDM
=> Add ibis.iSDM

README.md
https://github.com/Plant-for-the-Planet-org/FireAlert
=> Add FireAlert

README.md
https://github.com/EnAccess/OpenSmartMeter
=> Add OpenSmartMeter

README.md
https://gitlab.com/foodsharing-dev/foodsharing
=> Add foodsharing

README.md
- [Scout](https://github.com/WildMeOrg/scout)
- [Scoutbot](https://github.com/WildMeOrg/scoutbot)
=> add Scout and Scoutbot, connected Wildbook and WBIA

README.md
https://github.com/maRce10/baRulho
=> Add baRulho

education.md
https://github.com/DOI-USGS/python-for-hydrology
=> Add python-for-hydrology

README.md
https://github.com/DavidVeld/CarboLifeCalc
=> Add CarboLifeCalc

education.md
https://github.com/MetOffice/PyPRECIS
=> Add PyPRECIS

README.md
https://github.com/ECCC-MSC/msc-animet
=> Add MSC AniMet

README.md
https://github.com/ECCC-MSC/msc-pygeoapi
=> Add msc_pygeoapi

README.md
https://github.com/WAM2layers/WAM2layers
=> Add WAM2layers

README.md
https://github.com/Bonface-Osoro/saleos
=> Add saleos

README.md
https://github.com/ONEARMY/community-platform
=> Add ONEARMY

README.md
[https://github.com/Boavizta/cloud-scanner]
- [x ] The projects is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).
=> Added CloudScanner to the list of resources

README.md
Update klimatkollen's description to clarify that it's focusing on Sweden.
[https://www.klimatkollen.se/in-english](https://www.klimatkollen.se/in-english)
=> Update README.md - update klimatkollen

README.md
https://github.com/cal-adapt/climakitae
=> Add Climakitae

README.md
https://github.com/USDA-ARS-ACSL/MAIZSIM
Many citations: https://scholar.google.com/scholar?hl=de&as_sdt=0%2C5&q=MAIZSIM&btnG=
=> Add MAIZSIM

README.md
https://github.com/cropbox/Cropbox.jl
=> Add Cropbox.jl

README.md
https://github.com/AgriculturalModelExchangeInitiative/PyCrop2ML
=> Add PyCrop2ML

README.md
https://github.com/teikei/teikei
=> Add Teikei

README.md
https://github.com/FoodOntology/foodon
=> Add FOODON

README.md
https://github.com/Open-Agriculture/AgIsoStack-plus-plus
=> Add AgIsoStack-plus-plus

README.md
https://github.com/precision-sustainable-ag/dst-selector
=> Add Cover Crop Species Selector

education.md
https://github.com/soilwater/pynotes-agriscience
=> Add PyNotes in Agriscience

README.md
https://github.com/hanecakr/fellingdater
=> Add fellingdater

README.md
https://github.com/Ingenjorsarbete-For-Klimatet/ifk-smhi
=> Add ifk-smhi

README.md
https://github.com/environmentalinformatics-marburg/tubedb
=> Add TubeDB

README.md
https://github.com/chguiterman/dfoliatR
=> Add dfoliatR

README.md
https://gitlab.com/bonsamurais/bonsai/util/ipcc
=> Add bonsai_ipcc

README.md
https://github.com/wildlife-dynamics/ecoscope
=> Add Ecoscope

education.md
https://github.com/luiscruz/course_sustainableSE
=> Add Sustainable Software Engineering

README.md
https://github.com/Green-Software-Foundation/if
=> Add Impact Framework

README.md
https://github.com/Iniciativa-Climatica-Mexico/Net-Zero-Citizens
=> Add Net Zero Citizens

README.md
https://github.com/SPF-OST/optihood
=> Add optihood

README.md
https://github.com/IWUGERMANY/DIBS---Dynamic-ISO-Building-Simulator
=> Add Dynamic ISO Building Simulator

README.md
https://github.com/ugr-sail/sinergym
=> Add Sinergym

README.md
https://github.com/actris-cloudnet/cloudnetpy
=> Add CloudnetPy

README.md
https://github.com/Deltares-research/FloodAdapt
=> Add FloodAdapt

README.md
https://github.com/CliMA/ClimaLand.jl
=> Add ClimaLand.jl

README.md
https://github.com/ausocean/openfish
=> Add OpenFish

README.md
https://github.com/global-healthy-liveable-cities/global-indicators
=> Add Global Healthy and Sustainable Cities Indicators

README.md
https://github.com/nismod/infra-risk-vis
=> Add Infrastructure Risk Visualisation Tool

README.md
https://github.com/bcgov/CCISS_ShinyApp
=> Add Climate Change Informed Species Selection

README.md
https://github.com/allfed/allfed-integrated-model
=> Add ALLFED Integrated Food System Model

README.md
https://github.com/ClarkCGA/UDef-ARP
=> Add UDef-ARP

README.md
https://github.com/ebalogun01/EV-EcoSim
=> Add EV-EcoSim

README.md
https://github.com/OurPlanscape/Planscape
=> Add Planscape

README.md
https://github.com/hollorol/RBBGCMuso
=> Add RBBGCMuso

README.md
https://github.com/TimoDiepers/timex
=> Add timex_lca

README.md
https://github.com/NREL/ComStock
=> Add ComStock

README.md
https://github.com/NOAA-GFDL/icebergs
=> Add Icebergs

README.md
[timex_lca](https://github.com/TimoDiepers/timex)
=> Move timex_lca to LCA subsection

README.md
https://github.com/NREL/BuildingMOTIF
=> Add BuildingMOTIF

README.md
[https://github.com/flechtenberg/pulpo]
=> Add pulpo to open source LCA tools

README.md
https://github.com/e-mission/e-mission-phone
=> Add e-mission

README.md
https://github.com/AquaAuma/FishGlob_data
=> Add FishGlob_data

README.md
https://github.com/ECMWFCode4Earth/TropiDash
=> Add TropiDash

README.md
https://github.com/jaychempan/Awesome-LWMs
=> Add Awesome Large Weather Models

education.md
https://github.com/gmdsi/GMDSI_notebooks
=> Add Decision Support Modelling Notebooks

README.md
https://github.com/kartevonmorgen/kartevonmorgen.ts
=> Add kartevonmorgen

README.md
https://github.com/cozy/coachCO2
=> Add CoachCO2

README.md
https://github.com/geco-bern/ingestr/
=> Add ingestr

README.md
https://github.com/opengeos/HyperCoast
=> Add HyperCoast

education.md
https://github.com/floriscalkoen/CoastalCodeBook
=> Add Coastal Dynamics Open Codebook

README.md
https://github.com/project-pareto/project-pareto
=> Add PARETO

education.md
https://github.com/ProjectPythia/radar-cookbook
=> Add Radar Cookbook

education.md
https://github.com/ProjectPythia/landsat-ml-cookbook
=> Add Landsat ML Cookbook

README.md
https://github.com/ARM-DOE/pyart
=> Add Py-ART

README.md
https://github.com/CyanideCN/PyCINRAD
=> Add PyCINRAD

README.md
https://git.gfz-potsdam.de/fernlab/products/furuno/wrainfo
=> Add WRaINfo

README.md
https://github.com/genai-impact/ecologits
=> Add EcoLogits

README.md
https://github.com/ecmwf/magics
=> Add magics

README.md
https://github.com/ecmwf/eccodes
=> Add eccodes

README.md
https://github.com/gmlc-dispatches/dispatches
=> Add DISPATCHES

README.md
https://github.com/adcirc/adcirc
=> Add ADCIRC

README.md
**Insert URLs to the project here:** https://github.com/transition-zero/tz-client
=> Add TransitionZero Python Client

README.md
**Insert URLs to the project here:** https://github.com/ImperialCollegeLondon/wsi
=> Add WSIMOD

README.md
**Insert URLs to the project here:** https://github.com/WildlifeDatasets/wildlife-datasets
=> Add WildlifeDatasets

README.md
**Insert URLs to the project here:** https://github.com/mdtanker/polartoolkit
=> Add polartoolkit

README.md
**Insert URLs to the project here:** https://github.com/CryoInTheCloud/CryoCloudWebsite
=> Add CryoInTheCloud

README.md
**Insert URLs to the project here:** https://github.com/UMR-CNRM/EPyGrAM
=> Add EPyGrAM

README.md
**Insert URLs to the project here:** https://github.com/osdg-ai/osdg-data
=> Add OSDG Community Dataset

README.md
**Insert URLs to the project here:** https://github.com/podaac/hydrocron
=> Add Hydrocron

README.md
**Insert URLs to the project here:** https://github.com/opendcs/opendcs
=> Add OpenDCS

README.md
**Insert URLs to the project here:** https://github.com/carboniferio/carbonifer
=> Add carbonifer

README.md
**Insert URLs to the project here:** https://github.com/gbif/pygbif
=> Add pygbif

README.md
**Insert URLs to the project here:** https://github.com/SWOT-community/SWOT-OpenToolkit
=> Add SWOT-OpenToolkit

README.md
**Insert URLs to the project here:** https://github.com/pik-copan/pyunicorn
=> Add pyunicorn

README.md
**Insert URLs to the project here:** https://github.com/funecology/fundiversity
=> Add fundiversity

README.md
**Insert URLs to the project here:** https://github.com/NINAnor/carbonviewer
=> Add CarbonViewer

README.md
https://github.com/google/ground-android
=> Add Ground for Android

README.md
**Insert URLs to the project here:** https://github.com/Deltares/pyflwdir
=> Add pyflwdir

README.md
**Insert URLs to the project here:** https://github.com/Chrismarsh/CHM
=> Add The Canadian Hydrological Model

README.md
**Insert URLs to the project here:** https://github.com/robwschlegel/heatwave3
=> Add heatwave3

README.md
**Insert URLs to the project here:** https://github.com/publicissapient-france/e-footprint
=> Add E-footprint model

README.md
**Insert URLs to the project here:** https://github.com/nci/scores
=> Add Scores

README.md
**Insert URLs to the project here:** https://github.com/Deltares/hydromt
=> Add HydroMT

README.md
**Insert URLs to the project here:** https://github.com/sitkatech/projectfirma
=> Add projectfirma

README.md
**Insert URLs to the project here:** https://github.com/CADWRDeltaModeling/BayDeltaSCHISM
=> Add BayDeltaSCHISM

README.md
**Insert URLs to the project here:** https://github.com/spatial-ews/spatialwarnings
=> Add spatialwarnings

README.md
**Insert URLs to the project here:** https://github.com/Rekyt/funrar
=> Add funrar

README.md
**Insert URLs to the project here:** https://github.com/julienmoeys/soiltexture
=> Add soiltexture

README.md
**Insert URLs to the project here:** https://github.com/rOpenGov/iotables/
=> Add iotables

README.md
Input–Output Models are not part of Life Cycle Assessment but are a subcategory of Industrial Ecology based on this Wikipedia Article:
https://en.wikipedia.org/wiki/Industrial_ecology
=> Cluster Input–Output Model Subcategory

education.md
**Insert URLs to the project here:** https://github.com/ETCE-LAB/teaching-material
=> Add Emerging Technologies for the Circular Economy

README.md
**Insert URLs to the project here:** https://github.com/fingreen-ai/greenlang
=> Add Greenlang

README.md
**Insert URLs to the project here:** https://github.com/Dark-Matter-Labs/circulaw
=> Add CircuLaw

README.md
**Insert URLs to the project here:** https://github.com/GFDRR/CCDR-tools
=> Add Climate & Disaster Risk Screening Tools

README.md
**Insert URLs to the project here:** https://github.com/VU-IVM/DamageScanner
=> Add DamageScanner

README.md
**Insert URLs to the project here:** https://github.com/ropensci/mregions2
=> Add mregions2

README.md
**Insert URLs to the project here:** https://github.com/Education4Climate/Education4Climate
=> Add Education4Climate

education.md
**Insert URLs to the project here:** https://github.com/SERVIR/SERVIR-Applied-Deep-Learning-Book
=> Add SERVIR Applied Deep Learning Book

README.md
**Insert URLs to the project here:** https://github.com/quintel/etsource
=> Add ETSource

README.md
**Insert URLs to the project here:** https://github.com/FixMyBerlin/atlas-app
=> Add Radverkehrsatlas

README.md
**Insert URLs to the project here:** https://github.com/alan-turing-institute/clim-recal
=> Add clim-recal

README.md
**Insert URLs to the project here:** https://github.com/Orion-AI-Lab/KuroSiwo
=> Add Kuro Siwo

README.md
**Insert URLs to the project here:** https://github.com/ioos/gliderpy
=> Add gliderpy

README.md
**Insert URLs to the project here:** https://github.com/sandialabs/Albany
=> Add MPAS-Albany

README.md
**[Environmental Data Science book](https://github.com/alan-turing-institute/environmental-ds-book)** 
=> Add Environmental Data Science book

README.md
**Insert URLs to the project here:** https://github.com/OPERA-Cal-Val/OPERA_Applications
=> Add OPERA Applications

README.md
**Insert URLs to the project here:** https://github.com/secondlaw-ai/skyrim
=> Add Skyrim

README.md
**Insert URLs to the project here:** https://github.com/emf-creaf/forestables
=> Add forestables

README.md
**Insert URLs to the project here:** https://github.com/ghislainv/riskmapjnr
=> Add riskmapjnr

README.md
**Insert URLs to the project here:** https://github.com/environmental-modeling-workflows/watershed-workflow
=> Add Watershed Workflow

README.md
**Insert URLs to the project here:** https://github.com/NCAR/noahmp
=> Add Noah-MP

README.md
**Insert URLs to the project here:** https://github.com/lorenzovngl/FoodExpirationDates
=> Add Food Expiration Dates

README.md
**Insert URLs to the project here:** https://github.com/Sahil1786/Petari
=> Add Petari

README.md
**Insert URLs to the project here:** https://github.com/microsoft/BatteryML
=> Add BatteryML

README.md
**Insert URLs to the project here:** https://github.com/Energinet-DataHub/greenforce-frontend
=> Add GreenForce

README.md
I did a restructuring the biosphere category using ChatGPT for inspiration. In principle, I only used ChatGPT to find new possible clusters. The final categorization was based entirely on my own analysis including some clusters I created by myself.  ChatGPT has also completely removed projects without mentioning.
=> Restructuring and introduction of several new subcategories in Biosphere.

README.md
**Insert URLs to the project here:** https://github.com/censusdis/censusdis
=> Add censusdis for Python access to U.S. Census data.

README.md, education.md
**Insert URLs to the project here:** https://github.com/CLIMAAX/crabook
=> Add Climate Risk Assessment Book

education.md
**Insert URLs to the project here:** https://github.com/iiasa/eccb2024
=> Add An introduction to Systematic conservation planning with prioritzr

README.md
**Insert URLs to the project here:** https://github.com/pepijn-devries/ECOTOXr
=> Add ECOTOXr

README.md
**Insert URLs to the project here:** https://github.com/mllam/neural-lam
=> Add Neural-LAM

README.md
**Insert URLs to the project here:** https://github.com/ecmwf-projects/ibicus
=> Add ibicus

README.md
**Insert URLs to the project here:** https://github.com/storm-fsv-cvut/smoderp2d
=> Add smoderp2d

README.md
**Insert URLs to the project here:** https://github.com/bcgov/wqbench
=> Add wqbench

README.md
**Insert URLs to the project here:** https://github.com/NCC-CNC/wheretowork/
=> Add Where to Work

README.md
**Insert URLs to the project here:** https://github.com/bcgov/shinyssdtools
=> Add shinyssdtools

README.md
**Insert URLs to the project here:** https://github.com/pepijn-devries/CopernicusMarine
=> Add CopernicusMarine

README.md
**Insert URLs to the project here:** https://github.com/LibreSolar/bms-c1
=> Add bms-c1

README.md
**Insert URLs to the project here:** https://github.com/ROVI-org/battery-data-toolkit
=> Add Battery Data Toolkit

README.md
**Insert URLs to the project here:** https://github.com/StavrosOrf/EV2Gym
=> Add EV2Gym

README.md
**Insert URLs to the project here:** https://github.com/bcgov/lcfs
=> Add Low Carbon Fuel Standard

README.md
@lappemic I had to fix some issues with the clustering of power systems as the last PR I merged into the main failed.The linter did not pass.Please have a quick look so we can merge it and get the website + ClimateTriage.com working again.Let's make more improvements to the clustering with more pull requests.  
The current clustering is based on what you did + some deep dive analysis I did until this morning.
=> Improve clustering of Energy Systems

README.md
Sorted the newly created `Energy Systems` clusters alphabetically for easier navigation.
=> Sort new `Energy Systems` clusters alphabetically

README.md
**Insert URLs to the project here:** https://github.com/incubateur-ademe/nosgestesclimat
=> Add Nos Gestes Climat

README.md
**Insert URLs to the project here:** https://github.com/PyPSA/pypsa-ariadne
=> Add PyPSA-DE

README.md
**Insert URLs to the project here:** https://github.com/NASA-IMPACT/veda-ui
=> Add VEDA Dashboard

README.md
**Insert URLs to the project here:** https://github.com/incubateur-ademe/impactco2
=> Add impactco2

README.md
**Insert URLs to the project here:** https://github.com/leppott/BioMonTools
=> Add BioMonTools

README.md
As discussed in the last community meeting here the population and poverty section. More projects are gone follow
=> Create Population and Poverty Section

README.md
**Insert URLs to the project here:** https://github.com/NIEHS/amadeus
=> Add amadeus

README.md
**Insert URLs to the project here:github.com/laem/cartes** 
=> Add Cartes.app to the list in the transportation section

README.md
**Insert URLs to the project here:** https://github.com/epiverse-trace/ColOpenData
=> Add ColOpenData

README.md
**Insert URLs to the project here:** https://github.com/socialincome-san/public
=> Add Social Income

README.md
**Insert URLs to the project here:** https://github.com/thinkingmachines/unicef-ai4d-poverty-mapping
=> Add UNICEF AI4D Relative Wealth Project

README.md
**Insert URLs to the project here:** https://github.com/UI-Research/mobility-from-poverty
=> Add Boosting Upward Mobility from Poverty

education.md
**Insert URLs to the project here:** https://github.com/CU-ESIIL/HYR-SENSE
=> Add HYR-SENSE

README.md
**Insert URLs to the project here:** https://github.com/AgRoMeteorologiaINTA/agroclimatico
=> Add agroclimatico

README.md
**Insert URLs to the project here:** https://github.com/walkerke/tidycensus
=> Add tidycensus

README.md
**Insert URLs to the project here:** https://gitlab.com/opendatabio/opendatabio
=> Add OpenDataBio

README.md
**Insert URLs to the project here:** https://github.com/Moore-Institute-4-Plastic-Pollution-Res/One4All
**Add R package and the backend of the project.**
=> Add Microplastic Data Portal

README.md
**Insert URLs to the project here:** https://github.com/hansenjohnson/WhaleMap
=> Add WhaleMap

README.md
**Insert URLs to the project here:** https://github.com/chuhousen/amerifluxr
=> Add ameriflux

README.md
**Insert URLs to the project here:** https://github.com/EcologyR/BlueCarbon
=> Add BlueCarbon

README.md
**Insert URLs to the project here:** https://github.com/CARDAMOM-framework/CARDAMOM
=> Add CARDAMOM

README.md
**Insert URLs to the project here:** https://github.com/TheoMichelot/moveHMM
=> Add moveHMM

education.md
**Insert URLs to the project here:** https://github.com/martavp/pv-textbook
=> Add Fundamentals of Solar Cells and Photovoltaic Systems Engineering

README.md
**Insert URLs to the project here:** https://github.com/Aalto-QuML/ClimODE
=> Add ClimODE

README.md
**Insert URLs to the project here:** https://github.com/NIEHS/chopin
=> Add chopin

README.md
**Insert URLs to the project here:** https://github.com/NIEHS/beethoven
=> Add BEETHOVEN

README.md
**Insert URLs to the project here:** https://github.com/kike-canaries/canairio_firmware
=> Add CanAirIO

README.md
**Insert URLs to the project here:** https://github.com/csiro-hydroinformatics/pybomwater
=> Add pybomwater

README.md
**Insert URLs to the project here:** https://github.com/klaasnicolaas/home-assistant-glow
=> Add Home Assistant Glow

README.md
**Insert URLs to the project here:** https://github.com/mcsc-impact-climate/FAF5-Analysis
=> Add FAF5-Analysis

README.md
**Insert URLs to the project here:** https://github.com/MNeverOff/wee-forest
All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech) 
**The project does not show any usage indicator but the documentation and website quality is so good that I would still list it.**
=> Add WeeForest

README.md
**Insert URLs to the project here:** https://github.com/kausaltech/kausal-paths
=> Add Kausal Paths

README.md
**Insert URLs to the project here:** https://github.com/SAP/power-monitoring-tool-for-macos
=> Add Power Monitor

README.md
**Insert URLs to the project here:** https://github.com/ioos/Cloud-Sandbox
=> Add IOOS Cloud Sandbox

README.md
**Insert URLs to the project here:** https://github.com/ices-tools-dev/echoSMs
The download numbers show some level of external usage: https://pypistats.org/packages/echosms
=> Add echoSMs

README.md
**Insert URLs to the project here:** https://github.com/egagli/sar_snowmelt_timing
=> Add sar_snowmelt_timing

README.md
**Insert URLs to the project here:** https://github.com/hydrologie/xhydro
=> Add xHydro

README.md
**Insert URLs to the project here:** https://github.com/DOI-USGS/delaware-basin-story
=> Add Delaware River Basin Story

README.md
**Insert URLs to the project here:** https://github.com/ices-tools-prod/icesSAG
=> Add icesSAG

README.md
**Insert URLs to the project here:** https://github.com/dsgrid/dsgrid
=> Add dsgrid

README.md
**Insert URLs to the project here:** https://github.com/KTH-dESA/OSeMBE_ECEMF
=> Add OSeMBE_ECEMF

README.md
**Insert URLs to the project here:** https://github.com/ropensci/rOPTRAM
=> Add rOPTRAM

README.md
**Insert URLs to the project here:** https://github.com/UXARRAY/uxarray
=> Add uxarray

README.md
**Insert URLs to the project here:** https://github.com/opendata-apps/mantis
=> Add Gottesanbeterin Gesucht

README.md
**Insert URLs to the project here:** https://github.com/DOI-USGS/flow-tiles
=> Add flow-tiles

README.md
**Insert URLs to the project here:** https://github.com/MfN-Berlin/naturblick-ios
=> Add Naturblick iOS

README.md
**Insert URLs to the project here:** https://github.com/ropensci/traits
=> Add traits

README.md
**Insert URLs to the project here:** https://github.com/DOI-USGS/gw-conditions
=> Add gw-conditions

README.md
**Insert URLs to the project here:** https://github.com/DOI-USGS/COAWST
=> Add COAWST

README.md
**Insert URLs to the project here:** https://github.com/instrat-pl/pypsa-pl
=> Add PyPSA-PL

README.md
**Insert URLs to the project here:** https://github.com/microsoft/aurora
=> Add Aurora

README.md
**Insert URLs to the project here:** https://github.com/rebase-energy/enerflow
=> Add enerflow

README.md
**Insert URLs to the project here:** https://github.com/RobelTakele/AquaBEHER
=> Add AquaBEHER

README.md
**Insert URLs to the project here:** https://github.com/Gromopo/GroMoPo
=> Add GroMoPo

README.md
We have a [github repo](https://github.com/open-pv/website) and our actual website at https://www.openpv.de/
The website shows a growing user base, which is also visible by looking at issues that are created by people from outside the project. The code itself is not used by anyone yet, as far as I know. 
=> Add OpenPV

README.md
**Insert URLs to the project here:** https://github.com/Cidree/forestdata
=> Add forestdata

README.md
**Insert URLs to the project here:** https://github.com/clessig/atmorep
=> Add AtmoRep

README.md
**Insert URLs to the project here:** https://github.com/icepack/icepack
=> Add icepack

README.md
**Insert URLs to the project here:** https://github.com/mvdh7/calkulate
=> Add Calkulate

README.md
**Insert URLs to the project here:** https://github.com/munterfi/glacier-flow-model
=> Add Glacier flow model

README.md
**Insert URLs to the project here:** https://github.com/DataBytes-Organisation/Project-Echo
=> Add Project Echo

README.md
A new version of the AquaBEHER R package (v1.4.0) is issued and released on CRAN with an updated description. The package now provide functionality to produce seasonal forecast of the onset and cessation of the wet season
**Insert URLs to the project here: https://github.com/RobelTakele/AquaBEHER** 
=> Update the description of AquaBEHER #825

README.md
**Insert URLs to the project here:** https://github.com/gfbio/gfbio-data-submission
=> Add GFBio Data Submission and Brokerage System

README.md
**Insert URLs to the project here:** https://github.com/sisl/PyroRL
=> Add PyroRL

README.md
**Insert URLs to the project here:** https://github.com/ichimomo/frasyr
=> Add frasyr

README.md
https://github.com/Akkudoktor-EOS/EOS
=> Add Energy System Simulation and Optimization (EOS) by AkkuDoktor

README.md
**Insert URLs to the project here:** https://github.com/pnnl/ConStrain
=> Add ConStrain

README.md
**Insert URLs to the project here:** https://github.com/SynxFlow/SynxFlow
=> Add SynxFlow

README.md
**Insert URLs to the project here:** https://github.com/WaterFutures/EPyT-Flow
=> Add EPyT-Flow

README.md
**Insert URLs to the project here:** https://github.com/tbnobody/OpenDTU
=> Add OpenDTU

README.md
**Insert URLs to the project here:** https://github.com/spine-tools/SpineOpt.jl
=> Add SpineOpt.jl

README.md
**Insert URLs to the project here:** https://github.com/open-pv/simshady
=> Add SimShady

README.md
**Insert URLs to the project here:** https://code.mpimet.mpg.de/projects/cdo
=> Add Climate Data Operators

README.md
**Insert URLs to the project here:** https://github.com/dbeaudoinfortin/NAPSDataAnalysis
=> Add NAPS Data Analysis Toolbox

docs/overrides/main.html, mkdocs.yml
Follow up of #886 
Implements analytics script to be executed only in prod.
=> Update analytics script to execute only in production

README.md
**Insert URLs to the project here:** https://github.com/ProjectBabbler/ebird-api
=> Add eBird API

README.md
**Insert URLs to the project here:** https://github.com/ciceroOslo/ciceroscm
=> Add ciceroscm

README.md
**Insert URLs to the project here:** https://github.com/PhilipMostert/PointedSDMs
=> Add PointedSDMs

README.md
**Insert URLs to the project here:** https://github.com/nicovank/Energy-Languages
=> Add Energy Efficiency in Programming Languages

README.md
**Insert URLs to the project here:** https://github.com/OceanParcels/plasticparcels
=> Add plasticparcels

README.md
**Insert URLs to the project here:** https://github.com/Big-Biodiversity-Collaborative/SwallowtailClimateChange
=> Add Swallowtail Climate Change

README.md
**Insert URLs to the project here:** https://github.com/NREL/InSPIRE
=> Add InSPIRE

README.md
**Insert URLs to the project here:** https://github.com/ie3-institute/OSMoGrid
=> Add OSMoGrid

README.md
**Insert URLs to the project here:** https://github.com/VILLASframework/node
=> Add VILLASnode

README.md
**Insert URLs to the project here:** https://github.com/andrewlyden/PyPSA-GB
=> Add PyPSA-GB

education.md
**Insert URLs to the project here:** https://github.com/PV-Tutorials/pv-tutorials.github.io
=> Add pv-tutorials

README.md
**Insert URLs to the project here:** https://github.com/OpenTreeOfLife/opentree
=> Add Open Tree of Life

README.md
**Insert URLs to the project here:** https://github.com/germinateplatform/germinate-vue
=> Add Germinate

README.md
**Insert URLs to the project here:** https://github.com/NetFlora/Netflora
=> Add Netflora

README.md
**Insert URLs to the project here:** https://github.com/gabriel-russo/cbers4asat
=> Add cbers4asat

README.md
**Insert URLs to the project here:** https://github.com/fredliporace/cbers-2-stac
=> Add cbers-2-stac

README.md
**Insert URLs to the project here:** https://github.com/RolnickLab/OpenForest
=> Add OpenForest

README.md
**Insert URLs to the project here:** https://github.com/climate-service-center/index_calculator
=> Add index_calculator

README.md
**Insert URLs to the project here:** https://github.com/inbo/niche_vlaanderen
=> Add Niche Vlaanderen

README.md
**Insert URLs to the project here:** https://github.com/quintel/etlocal
=> Add ETLocal

README.md
**Insert URLs to the project here:** https://github.com/birdnet-team/birdnetR
=> Add birdnetR

README.md
**Insert URLs to the project here:** https://github.com/bmvandoren/Nighthawk
=> Add Nighthawk

README.md
**Insert URLs to the project here:** https://github.com/DBD-research-group/BirdSet
=> Add BirdSet

README.md
**Insert URLs to the project here:** https://github.com/maRce10/warbleR
=> Add warbleR

README.md
**Insert URLs to the project here:** https://github.com/birdnet-team/birdnet
=> Add birdnet

README.md
**Insert URLs to the project here:** https://github.com/woheller69/whoBIRD
=> Add whoBIRD

README.md
**Insert URLs to the project here:** https://github.com/correctiv/grundwasser-data
=> Add grundwasser-data

README.md
**Insert URLs to the project here:** https://github.com/salmonwatersheds/tech-report
=> Add Pacific Salmon Explorer

README.md
**Insert URLs to the project here:** https://github.com/woudc/woudc-data-registry
=> Add WOUDC Data Registry

README.md
**Insert URLs to the project here:** https://github.com/inrae/hubeau
=> Add hubeau

README.md
**Insert URLs to the project here:** https://github.com/fathomnet/fathomnet-py
=> Add fathomnet-py

README.md
**Insert URLs to the project here:** https://github.com/9505-PNNL/wmpy_power
=> Add wmpy-power

README.md
**Insert URLs to the project here:** https://github.com/ichthyop/ichthyop
=> Add Ichthtyop

README.md
**Insert URLs to the project here:** https://github.com/VolpeUSDOT/FHWA-DANATool
=> Add FHWA's DANA Tool

README.md
**Insert URLs to the project here:** https://github.com/TUMFTM/REVOL-E-TION
=> Add REVOL-E-TION

README.md
**Insert URLs to the project here:** https://github.com/alumet-dev/alumet
=> Add ALUMET

README.md
**Insert URLs to the project here:** https://github.com/HarvestStat/HarvestStat
=> Add HarvestStat

README.md
**Insert URLs to the project here:** https://github.com/Vizzuality/skytruth-30x30
=> Add SkyTruth 30x30 Tracker

README.md
**Insert URLs to the project here:** https://github.com/usetania/tania-core
=> Add The Farmer Journal

README.md
**Insert URLs to the project here:** https://github.com/iiasa/RE4AFAGRI_platform
=> Add RE4AFAGRI

README.md
**Insert URLs to the project here:** https://github.com/polca/pathways
=> Add pathways

README.md
**Insert URLs to the project here:** https://github.com/Vizzuality/landgriffon
=> Add Land Griffon

README.md
**Insert URLs to the project here:** https://github.com/bcgov/castor
=> Add Castor

README.md
**Insert URLs to the project here:** https://github.com/openinframap/openinframap
=> Add Open Infrastructure Map

README.md
**Insert URLs to the project here:** https://github.com/amanzi/amanzi
=> Add Amanzi

README.md
**Insert URLs to the project here:** https://github.com/ropensci/rcites/
=> Add rcites

README.md
**Insert URLs to the project here:** https://github.com/bcgov/invasivesbc
=> Add Invasive Species BC

README.md
**Insert URLs to the project here:** https://github.com/kleis-technology/lcaac
=> Add LCA as Code

README.md
**Insert URLs to the project here:** https://github.com/bcgov/ssdtools
=> Add ssdtools

README.md
**Insert URLs to the project here:** https://github.com/fieldsoftheworld/ftw-baselines
=> Add Fields of The World

README.md
**Insert URLs to the project here:** https://github.com/FluvialGeomorph/fluvgeo
=> Add fluvgeo

README.md
**Insert URLs to the project here:** https://github.com/samuelrince/awesome-green-ai
=> Add Awesome Green AI

README.md
**Insert URLs to the project here:** https://github.com/bioscan-ml/BIOSCAN-5M
=> Add BIOSCAN-5M

README.md
**Insert URLs to the project here:** https://github.com/wlcrs/huawei_solar
=> Add huawei_solar

docs/blog/openclimatefund.md, mkdocs.yml
=> fix openclimatefund integration

README.md
**Insert URLs to the project here:** https://github.com/dida-do/eurocropsml
=> Add EuroCropsML

README.md
**Insert URLs to the project here:** https://github.com/pagraf/MagicBathyNet
=> Add MagicBathyNet

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/mcsc-impact-climate/Geo-FTADS-Analysis …
=> Add Geo-FTADS-Analysis

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/nasaharvest/street2sat …
=> Add street2sat

education.md
**Insert URL to the project you want to be reviewed here:** https://github.com/control-protection-grids-tudelft/Control-and-protection-of-HVDC-AC-electrical-grids-IEEE-IES-MOOC/
3. Listed project that provide donation option via Open Source Collective or GitHub Sponsors can by nominated via …
=> Add Control and protection of HVDC/AC electrical grids

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/opentripplanner/OpenTripPlanner …
=> Add OpenTripPlanner

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/StephanJoubert/home_assistant_solarman …
=> Add Solarman integration

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/FL550/dwd_weather …
=> Add dwd_weather

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/MindFreeze/ha-sankey-chart …
=> Add Sankey Chart Card

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/alan-turing-institute/cloudcasting …
=> Add cloudcasting

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/CJNE/ha-myenergi …
=> Add myenergi for Home Assistant

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/slipx06/sunsynk-power-flow-card …
=> Add Sunsynk-Power-Flow-Card

README.md
**Insert URL to the project you want to be reviewed here: [ChaosBench](https://github.com/leap-stc/ChaosBench)**  …
=> add chaosbench

README.md
**Insert URL to the project you want to be reviewed here:**  https://github.com/sumn2u/deep-waste-app …
=> Add Deep Waste

README.md
3. Listed project that provide donation option via Open Source Collective or GitHub Sponsors can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently supported can be found [here](https://opensustain.tech/spreadsheet/). …
=> WRFtailor: Tailoring and modification of the WRF model input data

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/fboerman/jao-py …
=> Add jao-py

README.md
3. Listed project that provide donation option via Open Source Collective or GitHub Sponsors can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently supported can be found [here](https://opensustain.tech/spreadsheet/). …
=> Add ENERGYDATA.INFO

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/BerkeleySandProject/sandmining-watch …
=> Add Sand Mining Watch

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/wildflowai/platform …
=> Add wildflow

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/SanliFaez/FAIR-Battery …
=> Add FAIR-Battery

README.md
**Insert URL to the project you want to be reviewed here:** https://gitlab.com/sunpeek/sunpeek …
=> Add SunPeek

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/sachit27/greenR …
=> Add greenR

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/osmcode/osmcoastline …
=> Add OSMCoastline

README.md
Updated the README to include helpful links related to Toxicology resources
=> Update README.md with Toxicology resources

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/KIOS-Research/LeakDB …
=> Add LeakDB

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/weecology/PortalData …
=> Add PortalData

README.md
**Insert URL to the project you want to be reviewed here:** https://codeberg.org/FBRC/RFB-dev-kit …
=> Add RFB-dev-kit

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/enbility/eebus-go …
=> Add eebus-go

README.md
**Insert URL to the project you want to be reviewed here:** [earth-osm](https://github.com/pypsa-meets-earth/earth-osm) …
=> Add earth-osm

README.md
- [ x] The project is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).
3. Listed project …
=> Added BoaviztAPI

README.md
**Insert URL to the project you want to be reviewed here:** A Large Curated Image Dataset Enabling AI for Biodiversity …
=> Add BioTrove

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/open-energy-transition/Awesome-Electric-Grid-Mapping
3. Listed project that provide donation option via Open Source Collective or GitHub Sponsors can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently …
=> Add Awesome Electric Grid Mapping

README.md
3. Listed project that provide donation option via Open Source Collective or GitHub Sponsors can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently supported can be found [here](https://opensustain.tech/spreadsheet/). …
=> Add Extreme Weather Bench

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/OSeMOSYS/osemosys_global …
=> Add osemosys_global

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/balmorelcommunity/Balmorel …
=> Add Balmorel

README.md
https://eelib.readthedocs.io/en/release/
The project is
=> Integrate eELib project to list

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/etsap-TIMES/xl2times …
=> Add xl2times

.github/pull_request_template.md
Add the option to nominate a project by the people maintained in the comments.
=> Improve PR template for OpenClimate.fund

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/TNO/ChaProEV …
=> Add ChaProEV

README.md
**Insert URL to the project you want to be reviewed here:** https://gitlab.lrz.de/energy-management-technologies-public/open-data-collection
3. Listed project that provide donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently supported can be found …
=> Add TUM-EMT Open Data Collection

README.md
**Insert an project you want to nominate for a …
=> Add Terraware Web

README.md
**Insert URL to the project you want to be reviewed here:** https://gitlab.com/sesit/copper
**Insert an project …
=> Add COPPER

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/offgridai-us/cost-calculator …
=> Add offgridai

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/open-energy-transition/grid-mapping-starter-kit
3. Listed project that provide donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All project currently supported can be found …
=> Add Grid Mapping Starter Kit

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/AndrewIOM/bristlecone
**Insert an …
=> Add Bristlecone

README.md
**Insert an project you want to nominate for a …
=> Add SustainGym

README.md
**Insert an project you want to nominate for a …
=> Add CspStandSegmentation

README.md
**Insert an project you want to nominate for a …
=> Add PASTIS

README.md
https://github.com/ait-energy/IESopt.jl
=> Add IESopt.jl

README.md
=> Add OpenSynth

README.md
=> Add StationBench

README.md
=> Add Arbimon

README.md
=> Add Ecobricks

README.md
=> Add Restor Foundation Tree Crown Delineation Pipeline

docs/analytics.md
Fix Analytics and improve text.
=> Fix Analytics

README.md
=> Add GermanRenewableEnergy

README.md
=> Add rlandfire

README.md
HVDC lines directly connect the electrical grid between countries and regions enabling the exchange of renewable energy 
3. Listed projects that provide a …
=> Add HVDC-Wise

README.md
=> Add PyPSA-KZ

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/fl4p/batmon-ha
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All …
=> Add Homeassistant E3DC Integration

README.md
=> add skygpt

README.md
**[EcoSurf Analyser](https://github.com/les-enovateurs/estimate-good-website)** 
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All projects …
=> Add EcoSurf Analyser

README.md
https://github.com/tokami/TropFishR
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All projects currently supported can be found …
=> Add TropFishR

README.md
=> Add AI Wattch

README.md
https://www.dailyerosion.org/
https://github.com/dailyerosion/dep
3. Listed projects that provide a donation option can by nominated via …
=> Add Daily Erosion Project

README.md
https://github.com/EMODnet/EMODnetWCS
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All projects currently supported can be found …
=> Add EMODnetWCS

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/USDA-VS/GenoFLU
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All …
=> Add GenoFLU

README.md
https://github.com/FINPLAN-Model/FINPLAN-UI
1. Issues labeled as Good First Issue will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community members to your project.
3. Listed projects that provide a donation option can by nominated via [OpenClimate.fund](https://openclimate.fund/). All projects currently supported can be found …
=> Add FINPLAN

README.md
https://gitlab.com/dlr-ve/esy/vencopy/vencopy
=> Add venco.py

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/NREL/H2Integrate
=> Add H2Integrate

README.md
=> Add ReWaterGAP

README.md
https://github.com/NCAR/miles-credit
=> Add CREDIT

README.md
=> Add BatDetect2

README.md
=> Add EcoNicheS

education.md
=> Add OpenRefine-ecology

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/fsspec/kerchunk
Context: 
is highly relevant for climate science because it provides an efficient, scalable, and flexible way to store and access large, multi-dimensional arrays — the core data format used in climate models and observational datasets. 
2. All new projects listed will be posted on our …
=> Add kerchunk

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/earth-mover/icechunk 
=> Add icechunk

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/open-forest-observatory/tree-detection-framework
=> Add tree-detection-framework

README.md
=> Add eo-tides

README.md
=> Add NDBC API

education.md
=> Add Harnessing the Power of Pangeo

README.md
=> Add Biowatch

README.md
https://github.com/uncscode/particula
=> Add Particula

README.md
https://github.com/open-energy-transition/demandcast
=> Add Electricity Demand Data

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/UMR-CNRM/snowtools
=> Add Snowtools

README.md
=> Add ccvi-data

README.md
=> Add TulipaEnergyModel to Energy System Modelling Frameworks

README.md
Excellent listing, thanks to the maintainers! It'd be great if you could include our tool CATS, which I deemed to fit best under the 'Emissions -> Carbon Intensity and Accounting' sub-section, hence I've placed it there in standard format (but it could go elsewhere if you deem it more suitable under another section).
**Insert URL to the project you want to be reviewed here:** https://github.com/GreenScheduler/cats
1. Issues labeled as **Good First Issue** will be visible on [ClimateTriage.com](https://climatetriage.com/). This is a great way to welcome new community …
=> Add CATS: the Climate-Aware Task Scheduler

README.md
=> Add bbousuite

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/timcera/swmmtoolbox
=> Add SWMManywhere

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/dspelaez/extended-wdm
=> Add eva3dm

README.md
=> Add pytreedb

README.md
=> Add Roseau Load Flow

README.md
https://github.com/PlantSimulationLab/Helios
=> Add Helios

README.md
https://github.com/NREL/celavi
=> Add CELAVI

README.md
https://github.com/Huracan-project/huracanpy
=> Add HuracanPy

README.md
Carbonara has moved to 
https://github.com/DigitalPebble/spruce
=> Renamed carbonara into spruce

README.md
=> Add MapYourGrid

README.md
**Insert URL to the project you want to be reviewed here: https://github.com/mapbiomas/user-toolkit** 
I opened an issue asking to add a license file.
=> Add Mapbiomas

README.md
Addressed Issue #35 .
Added "What?" and "How?" descriptions to all categories and subcategories.
- "What?" is a general explanation of the concept (think of answering "What is Life-cycle assessment?")
- "How?" is a concise summary of how the tools listed address that topic (think of answering "How do the tools tackle/help with Life-cycle assessment?)
Example:
> __What?__ A method for generating and storing electricity directly from sunlight.
> __How?__ These tools help simulate, model, and forecast photovoltaic energy output, including optical and ray-tracing simulations; analyze and visualize system data; support quality control; and interface with solar hardware like panels, inverters, and batteries.
__Citation:__ I manually went through all the projects, but used a combination of …
=> Fix #35: Description of Field and Topics 

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/nreca-bts/omf
=> Add Open Modeling Framework

README.md
=> Add Groundwater Accounting Platform

README.md
=> Add gen3sis

README.md
=> Add gbif.range

README.md
https://github.com/bc3LC/medusa
=> Add MEDUSA

README.md
https://github.com/hyex-research/AquaFetch
=> Add AquaFetch

README.md
https://github.com/NumericalMathematics/DispersiveShallowWater.jl
=> Add DispersiveShallowWater.jl

README.md
https://github.com/aemon-j/LakeEnsemblR
=> Add LakeEnsemblR

README.md
https://github.com/gridfm/gridfm-graphkit
=> Add GridFM

README.md
=> Add reformatters

README.md
https://github.com/IEC-61400-15/eya_def
=> Add IEC 61400-15-2 EYA DEF

README.md
https://github.com/OHI-Science/ohicor
- [x ] Active
=> Add OHICORE

README.md
=> Add animl-py

README.md
=> Add gediDB
