protontypes/open-sustainable-technology

README.md
This PR updates the url and description of the **pyam** package.
Beyond the scope of this PR, but there seems to be a bit of confusion between the "Modeling" section and the "Analysis" section - many of the entries in "Analysis" are really modelling frameworks (e.g., PyPSA, oemof, matpower, POMATO), whereas pyam and the Open Energy Platform (and possibly others in that section) are tools for analysis-and-visualization packages/tools (but not for creating the scenario results). A bit of a review and structuring/tagging might be helpful...
=> Update url and description of the pyam package

README.md
Hello Open Sustainable Technology!
I would like to propose the addition of [FarmOS](https://farmos.org/).
FarmOS is a web application for farm management, planning, and record keeping. The software provides standard platform for agricultural data collection and management. The FarmOS code is hosted on Github [https://github.com/farmOS/farmOS](https://github.com/farmOS/farmOS).
=> Add FarmOS

docs/community.md
[Public Lab](https://publiclab.org/) is a community and a non-profit, democratizing science to address environmental issues that affect people.
The organization contributes to community science and environmental justice initiatives and develops open technologies.
Public Lab's code is open source and hosted on [Github](https://github.com/publiclab).
=> Add Public Lab

README.md
Adding the FlexMeasures platform, which allows energy service companies (ESCos) to add energy flexibility services to their stack.
FlexMeasures acts as a data science backend, where forecasting and optimized intra-day planning can be run and the results are available through an API. Some basic forecasting & scheduling algorithms are built-in, we'll soon make it possible to plugin custom ones.
Read more on http://flexmeasures.readthedocs.org
My Tweet: A platform for building #energyflexibility services with forecasting and scheduling, written in Python & offering an API inspired by @USEFsmartenergy.
=> add the FlexMeasures project

README.md
Insert URLs to the project(s) here: 
- https://github.com/open-meteo/open-meteo
- https://open-meteo.com/en/docs
This is a follow up on #95.
Explain what this list is about and why it should be included here:
Open-Meteo is an open-source weather forecast API. Global and regional weather models offer 7 days forecasts in hourly resolution. With more than 40 weather variables, Open-Meteo covers everything for agriculture, house-automation, tourism, solar and wind energy forecasting. Additionally more than 60 years of historical weather data are available to explore patterns in climate change.
Open-Meteo is build on top of open-data and is using the most trusted weather data from national weather services. APIs are available for free for non-commercial use and can be used without an API key. …
=> Add Open-Meteo

README.md
I migrated MODISTools back to @bluegreen-labs to retain more control as community engagement is low for niche packages on rOpenSci.
[ Your URLs ]
[ Your Text ]
=> correct link R MODISTools

README.md
Hi! I was referred to this list, and since I couldn't find it on the list, I suggest adding it to the Curated Lists part. I am not affiliated.
**URLs to the project:**      
https://github.com/low-voltage-loadforecasting/low-voltage-loadforecasting.github.io
This list specifically addresses the Low-Voltage Load Forecasting field and seems to be a useful resource to keep updated with regard to available datasets. The maintainers welcome contributions of additional datasets which can be utilized in low-voltage load forecasting.
=> Adding Low-Voltage Load Forecasting Datasets to Curated Lists

README.md
Added two of our projects for energy measurement / estimation with detailed description directly in the PR.
Both tools are open source and help developers to wage the energy consumption of an application in different phases like installation, booting, runtime but also testing to get a better overview over the total cost of the application.
Hope you find them useful for the list :)
- https://github.com/green-coding-berlin/green-metrics-tool
- https://github.com/green-coding-berlin/eco-ci-energy-estimation
- An open source suite to measure, display and compare software energy and CO2 consumption for containerized software. External power meters as well as RAPL and also …
=> Adding Green Metrics Tool and Eco-CI

README.md
https://github.com/os-climate/physrisk
Physrisk is primarily designed to run 'bottom-up' calculations that model the impact of climate hazards on large numbers of individual assets (including natural) and operations.
=> Add physrisk

.github/pull_request_template.md
The PR template was changed so that the contribution guide link and a summary of the requirements is been visible to every new contributor.
=> Add requirements to be listed to the PR template

README.md
https://github.com/pik-primap/unfccc_di_api
Data access to the total greenhouse gas emissions by country reported to the United Nations Framework Convention on Climate Change (UNFCCC).
I removed an older project with the same goal that is not maintained anymore and is not compatible with the current version of the UNFCCC API.
=> ADD UNFCCC DI API

README.md
https://github.com/arup-group/a-carbon-tool
An open source web application that enables users to estimate embodied carbon equivalent content from Building Information Models.
=> Add A Carbon Tool

README.md
https://github.com/openclimatefix/Open-Source-Quartz-Solar-Forecast
The aim of the project is to build an open source PV forecast that is free and easy to use.
=> Add Quartz Solar Forecast

README.md
https://github.com/USEPA/haztrak
A web application that aims to illustrate how hazardous waste management software can interface with EPA's e-Manifest systems to track hazardous waste electronically from cradle-to-grave.
=> Add Haztrak

README.md
[carbonintensity-api](https://github.com/jnioche/carbonintensity-api) 
- Rust library to retrieve regional carbon intensity data from the UK National Grid.
=> Added carbon intensity API

README.md
https://github.com/wincowgerDEV/OpenSpecy-package
Raman and (FT)IR spectral analysis tool for plastic particles and other environmental samples.
=> Add OpenSpecy

README.md
https://github.com/MazamaScience/AirMonitor
Utilities for working with hourly air quality monitoring data with a focus on small particulates PM2.5.
=> Add AirMonitor

README.md
https://github.com/chjch/pylusat
Intends to provide users with tools that can be used to conduct land-use suitability analysis.
=> Add PyLUSAT

README.md
https://github.com/USEPA/cam-api-portal
A suite of API's that EPA's Clean Air Markets Division provides to access the data collected to run programs designed to reduce air pollution from power plants.
=> Add Clean Air Markets API Portal

README.md
https://github.com/Thomasjkeel/jsmetrics
An open-source Python package containing implementations of various statistics and algorithms which have been developed to identify or characterise jet streams.
=> Add jsmetrics

README.md
https://github.com/observingClouds/pysonde
=> Add pySonde

README.md
https://github.com/earth-chris/earthlib-legacy
=> Add earthlib

README.md
https://github.com/xapple/waste_flow
=> Add waste_flow

README.md
[PyPSA-Eur-Sec](https://github.com/PyPSA/pypsa-eur-sec) (deprecated)
[PyPSA-Eur](https://github.com/pypsa/pypsa-eur)
"PyPSA-Eur-Sec v0.7.0 has been merged into PyPSA-Eur with version [v0.8.0](https://pypsa-eur.readthedocs.io/en/latest/release_notes.html). Please go to [PyPSA-Eur](https://github.com/pypsa/pypsa-eur) to run sector-coupling studies for the European energy system with PyPSA. This repository is now deprecated!"
=> Update links to PyPSA-Eur as PyPSA-Eur-Sec is now merged into PyPSA-Eur

README.md
https://github.com/cryotools/matilda
=> Add MATILDA

README.md
https://github.com/doserjef/spOccupancy
=> Add spOccupancy

README.md
https://github.com/cyschneck/centerline-width
=> Add Centerline-Width

README.md
https://github.com/ropensci/FedData
=> Add FedData

README.md
https://github.com/cisco-open/green-monitoring
=> Add Green Monitoring Stack for network and DC

README.md
https://github.com/prommis/prommis
Took me a bit of time to understand what this project does but the sustainability reference is clear in the use-case: https://prommis.readthedocs.io/en/latest/tutorials/diafiltration.html#case-study-separation-of-lithium-from-cobalt-via-diafiltration
=> Add prommis

README.md
https://github.com/pangeo-data/pangeo-docker-images
=> Add Pangeo Docker Images

README.md
https://github.com/ONEcampaign/climate-finance-package
Is the python package to get, clean, and work with international public climate finance.
I found some documention of this project and a really impressiv report that has been created with this open source data and tools:
Documentation:
https://datacommons.one.org/data/climate-finance-files
Report:
https://datacommons.one.org/climate-finance-files
=> Add climate-finance

README.md
https://github.com/HFAiLab/OpenCastKit
=> Add OpenCastKit

README.md
[Soil Freeze-thaw Model](https://github.com/NOAA-OWP/SoilFreezeThaw)
=> Add Soil Freeze-thaw Model

education.md
https://github.com/padasch/tutorial_digital_soil_mapping
=> Add Digital Soil Mapping

README.md
https://github.com/cell2fire/Cell2Fire
=> Add Cell2Fire

README.md
https://github.com/Vizzuality/mangrove-atlas
=> Add Mangrove Atlas

README.md
https://github.com/Vizzuality/heco-invest
Note: Project is still in beta but more details can be found [here](https://www.vizzuality.com/project/heco-invest)
=> Add HeCo Invest

README.md
https://github.com/dvelasquez/carbon-tools
=> Add Carbon Tools

README.md
https://github.com/AtlasOfLivingAustralia/volunteer-portal
=> Add DigiVol

README.md
https://github.com/Planteome/plant-trait-ontology
=> Add Plant Trait Ontology

README.md
https://github.com/climateinteractive/SDEverywhere
Note: This is a framework created for various climate simulator. The climate simulator repos are not public but all the websites are CC.
> [Climate Interactive](https://www.climateinteractive.org/) has been using SDEverywhere in production since 2019 for their popular simulation tools:
[En-ROADS](https://en-roads.climateinteractive.org/) — an online global climate simulator that allows users to explore the impact of policies on hundreds of factors like energy prices, …
=> Add SDEverywhere

README.md
https://github.com/cncf-tags/green-reviews-tooling
=> Add CNCF Green Reviews WG

README.md
https://github.com/JGCRI/helios
=> Add helios

README.md
https://github.com/NREL/altrios
=> Add ALTRIOS

education.md
https://github.com/US-GHG-Center/ams-2024-workshop
The website says © CC-By at left lower corner ^^
=> Add Using NASA Satellite Data for Real-Time Environmental Monitoring

README.md
https://github.com/GeoscienceAustralia/dea-notebooks
=> Add DEA Notebooks

README.md
https://github.com/Smithsonian/CCN-Data-Library
The open source license can be found here:
https://smithsonian.figshare.com/articles/dataset/Database_Coastal_Carbon_Library_Version_1_0_0_/21565671
=> Add Coastal Carbon Network Data Library

README.md
https://github.com/inaturalist/iNaturalistReactNative
=> Add iNaturalistReactNative

README.md
https://github.com/Clay-foundation/model
=> Add Clay Foundation Model

README.md
https://github.com/ACCESS-NRI/access-nri-intake-catalog
=> Add ACCESS-NRI Intake Catalog

README.md
https://github.com/google-research/neuralgcm
=> Add NeuralGCM

README.md
https://github.com/openenergymonitor/heatpumpmonitor.org
=> Add HeatpumpMonitor.org

README.md
https://github.com/ed-hawkins/climate-visuals
The license is not 100% clear and is only stated in the README. Since these graphics are used by thousands of people around the world, it is still a good fit from by point of view.
=> Add climate-visuals

README.md
https://github.com/ropensci/rvertnet
=> Add rvertnet

README.md
https://github.com/ScottLogic/Technology-Carbon-Standard
=> Add Technology-Carbon-Standard

README.md
https://github.com/thegridelectric/gw-scada-spaceheat-python
=> Add GridWorks SpaceHeat SCADA

README.md
https://github.com/climate-cooperative/home-energy-assessment-database
=> Add Home Energy Assessment Database

README.md
https://github.com/openmethane/openmethane-prior
The website can be visited here: https://openmethane.org/
=> Add OpenMethane

README.md
https://github.com/XavB64/lowtrip
=> Add lowtrip

README.md
https://github.com/brightway-lca/brightway2-data
=> Add Brightway2 data management

.github/workflows/post_mastodon.yml
Allows us to create Mastodon posts from commit messages on the main branch. This will allow us to post any new projects added to OpenSustain.tech to Mastodon, providing the community with a feed of newly listed projects.
When the commit message contains *https*, the entire commit message will be posted. 
Relates to issue #55
=> Add mastodon feed

README.md
Creates an entry under Emissions/Carbon Intensity for the Open-IMO-CII-Calculator library
[Open-IMO-CII-Calculator github](https://github.com/Etive-Mor/Open-IMO-CII-Calculator)
=> Adds Open-IMO-CII-Calculator

README.md
https://github.com/CSHS-CWRA/RavenPy
=> Add RavenPy

README.md
https://github.com/nismod/open-gira
=> Add Open Global Infrastructure Risk/Resilience Analysis

README.md
https://github.com/undp/climate-transparency
=> Add National Climate Transparency Tool

README.md
https://github.com/GarrettLab/HabitatConnectivity
=> Add geohabnet

README.md
https://github.com/NREL/GEOPHIRES-X
=> Add GEOPHIRES-X

README.md
https://github.com/CliMA/TurbulenceConvection.jl
=> Add TurbulenceConvection.jl

education.md
https://github.com/ECMWFCode4Earth/sketchbook-earth
I had to use google to find the deployed website: 
https://ecmwfcode4earth.github.io/sketchbook-earth/intro.html
=> Add Sketchbook Earth

README.md
https://github.com/MTES-MCT/monitorfish
=> Add Monitorfish

README.md
https://github.com/danwrisar/KMSIMG_NHS_EmissionsRecipeBook
=> Add The NHS Emission Quantification Recipe Book

README.md
https://github.com/usgs/pestpp
=> Add PEST++

README.md
https://github.com/NOAA-GFDL/FMScoupler
=> Add FMS Coupler

README.md
https://github.com/nychealth/EH-dataportal
=> Add NYC Environment and Health Data Portal

README.md
https://github.com/awslabs/sustainability-scanner
=> Add Sustainability Scanner

education.md
https://github.com/ProjectPythia/cmip6-cookbook
=> Add CMIP6 Cookbook

education.md
https://github.com/podaac/tutorials
=> Add PO.DAAC Tutorials

README.md
https://github.com/NVIDIA/earth2studio
=> Add Earth2Studio

README.md
**Insert URLs to the project here:** https://github.com/SchmidtDSE/plastics-prototype
=> Add Plastics Prototype

README.md
**Insert URLs to the project here:** https://github.com/tetratech/baytrends
=> Add baytrends

README.md
**Insert URLs to the project here:** https://github.com/M3Works/metloom
=> Add metloom

README.md
**Insert URLs to the project here:** https://github.com/GeoscienceAustralia/fc
=> Add Fractional Cover

README.md
**Insert URLs to the project here:** https://github.com/EcohydrologyTeam/ClearWater-riverine
=> Add ClearWater-Riverine

README.md
**Insert URLs to the project here:** https://github.com/OceanographyforEveryone/OpenCTD
=> Add OpenCTD

README.md
**Insert URLs to the project here:** https://github.com/Greater-Wellington-Regional-Council/Environmental-Outcomes-Platform
=> Add Environmental Outcomes Platform

README.md
https://github.com/WSWUP/gridwxcomp
=> Add gridwxcomp

README.md
**Insert URLs to the project here:** https://github.com/CEA-Liten/HeatPro
=> Add HeatPro

README.md
**Insert URLs to the project here:** https://github.com/miniufo/xinvert
=> Add xinvert

README.md
This PR addresses the reclustering of the broad category `Energy Systems` as disussed with @Ly0n.  This is a WIP an will further be refined and asked for review. Leaving it here for transparency and inputs on the process.
Approach is the same as mentioned in #695: Chatgpt provided the clustering idea and then assign the projects by hand to the new categories.
Categories to be refined:
- Energy Systems
I will update the progress here and ask for proper review once i finished from my side the first iteration.
=> Reclustering Energy Systems

README.md
**Insert URLs to the project here:** https://github.com/hydroframe/hf_hydrodata
=> Add hf_hydrodata

README.md
**Insert URLs to the project here:** https://github.com/WordPress/sustainability
=> Add WordPress Sustainability Handbook

README.md
**Insert URLs to the project here:** https://github.com/SalishSeaCast/SalishSeaNowcast
All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech) 
**I removed the the circulation from the section topic name as no all ocean models are just circulation models.**
=> Add SalishSeaNowcast and Rename Section To Ocean Models

README.md
**Insert URLs to the project here:** https://github.com/worldbank/blackmarblepy
All projects listed will be posted on our [Mastodon channel](https://mastodon.social/@opensustaintech) 
**Nighttime Lights are widely used to measure poverty, population but also human activity in protected areas.**
=> Add BlackMarblePy

.github/pull_request_template.md, .github/workflows/post_mastodon.yml, docs/overrides/main.html
Some smaller changes to the website:
1. Add our own unique #hashtag #opensustain to Mastodon 
2. Ask for donation in the OpenSustain.tech announcement 
3. Fix small typo in PR template.
=> New Hashtag. Ask for donation in announcement. Fix small typo in PR template

README.md
**Insert URLs to the project here:** https://github.com/codeforboston/home-energy-analysis-tool
=> Add Home Energy Analysis Tool

README.md
**Insert URLs to the project here:** https://github.com/jmcollin78/versatile_thermostat
=> Add Versatile Thermostat

README.md
The previous repo is deprecated. The latest version of the dataset is no longer stored in a repo, but the dataset is still CC based on this link: https://app.climatepolicyradar.org/terms-of-use
As suggested by @kdutia, I replaced the link with the methodology repository.
=> Fix Climate Policy Radar

README.md
**Insert URLs to the project here:** https://github.com/DOI-USGS/snow-to-flow
=> Add From Snow to Flow

README.md
**Insert URLs to the project here:** https://github.com/github/GreenSoftwareDirectory
=> Add GitHub's Green Software Directory

README.md
**Insert URLs to the project here:** https://github.com/OpenSenseAction/OPENSENSE_sandbox
=> Add OPENSENSE software sandbox

README.md
**Insert URLs to the project here:** https://github.com/statisticspoland/sdg-indicators-pl
=> Add Polish SDG reporting platform

README.md
**Insert URLs to the project here:** https://github.com/dataforgoodfr/quotaclimat
=> Add QuotaClimat

README.md
**Insert URLs to the project here:** https://github.com/MET-OM/metocean-stats
=> Add Metocean-stats

README.md
**Insert URLs to the project here:** https://github.com/jpbede/aioelectricitymaps
=> Add aioelectricitymaps

README.md
**Insert URLs to the project here:** https://github.com/carbon-intensity/api-definitions
Data is CC: 
https://carbon-intensity.github.io/api-definitions/#carbon-intensity-api-v2-0-0
=> Add Carbon Intensity API

README.md
**Insert URLs to the project here:** https://github.com/bbsBayes/bbsBayes2
=> Add bbsBayes2

README.md
**Insert URLs to the project here:** https://github.com/hotosm/hotosm-website
=> Add Humanitarian OpenStreetMap

README.md
**Insert URLs to the project here:** https://github.com/Open-ET/flux-data-qaqc
=> Add flux-data-qaqc

README.md
**Insert URLs to the project here:** https://github.com/JohnPaton/airbase
=> Add AirBase

education.md
**Insert URLs to the project here:** https://github.com/ECCO-Hackweek/ecco-2024
=> Add ECCO Hackweek 2024 Website

README.md
**Insert URLs to the project here:** https://github.com/RWTH-EBC/districtgenerator
=> Add DistrictGenerator

README.md
**Insert URLs to the project here:** https://github.com/pvlib/twoaxistracking
=> Add twoaxistracking

README.md
**Insert URLs to the project here:** https://github.com/EIAgov/BlueSky
**Note:** The project does not show usage because it is brand new, but because of the social/political relevance of the IEA open sourcing this, I think a usage indicator is not needed.
=> Add BlueSky

README.md
**Insert URLs to the project here:** https://github.com/CliDyn/climsight
=> Add Climate Foresight

README.md
**Insert URLs to the project here:** https://github.com/atodorov284/air-quality-forecast
=> Add Air Quality Forecast

README.md
**Insert URLs to the project here:** https://github.com/thermotools/thermopack
=> Add ThermoPack

README.md
**Insert URLs to the project here:** https://github.com/jorgecardleitao/private-jets
**Note:** The repo is not open source licensed but the paper released and all plots are Creative Commons Attribution 4.0: https://www.nature.com/articles/s43247-024-01775-z
Should we still accept the project? Our contribution guidelines only says that major parts of the project must be open source licensed.
=> Add Private Jet Flights

README.md
**Insert URLs to the project here:** https://github.com/C2SM-RCM/emiproc
=> Add Emiproc

README.md
Adding two links to Flexth and LibreWAter
**Insert URLs to the project here:** https://code.europa.eu/floods/floods-river/flexth https://codeberg.org/LibreWater/Acraea-Prototype
=> Add Flexth and LibreWAter

README.md
**Insert URLs to the project here:** https://github.com/damienallen/urban-heat
**Note:** The repo do not show any issues or usage indicators, but the web application works very well and I have tested it for different cities! The documentation could be better!
=> Add urban-heat

README.md
**Insert URLs to the project here:** https://github.com/Imageomics/pybioclip
=> Add pybioclip

README.md
**Insert URLs to the project here:** https://github.com/openmeteo/enhydris
=> Add Enhydris

.github/pull_request_template.md, .github/workflows/ecosystems_to_grist.py, .github/workflows/update_grist.yml, CONTRIBUTING.md, docs/blog/openclimatefund.md, docs/overrides/main.html, docs/presentations.md, docs/spreadsheet.md, mkdocs.yml
- Add OpenClimate.fund to PR template
- Random listing of funding options in Grist spreadsheet
- Update Grist data every day.
- Add OpenClimate.fund blog post 
- Add header for OpenClimate.fund
- Add all the presentation recorded in the last years to a separated section.
=> Integration of OpenClimate.fund content 

README.md
**Insert URLs to the project here:** https://github.com/earthrise-media/mining-detector
=> Add Gold Mine Detector

docs/privacy-policy.md, mkdocs.yml
Refers to #1027 
Add Privacy Policy to footer, including a copyright notice" Copyright &copy; Open Sustainable Technology Contributors"
As we do not use cookies, we do not need an annoying cookie banner.
=> Add Privacy Policy to Footer

docs/grist_spreadsheet_metadata.md
**Issue**
Github issue: https://github.com/protontypes/open-sustainable-technology/issues/798#issuecomment-2558104127
**Discussed solution**
As per https://github.com/protontypes/open-sustainable-technology/issues/798#issuecomment-2558104127, to start with, created a Markdown table with the Grist spreadsheet metadata descriptions/definitions to help the user to understand the source of the provided values.
**References**
Grist spreadsheet: https://docs.getgrist.com/doc/gSscJkc5Rb1Rw45gh1o1Yc
Script: https://github.com/protontypes/open-sustainable-technology/blob/main/.github/workflows/ecosystems_to_grist.py
Backend source: https://github.com/ecosyste-ms/ost
**Screenshot**
**Notes**
Some questions that came up while I was writing the definitions:
- For the "Organizations" sheet, should …
=> Grist spreadsheet metadata (column name) definitions/descriptions

README.md
**Insert URL to the project you want to be reviewed here:** https://github.com/jump-dev/open-energy-modeling-benchmarks …
=> Add open-energy-modeling-benchmarks

README.md
https://github.com/flixOpt/flixOpt
[ x] The project is active, documented, open source licensed, shows usage from external parties and is directly targeting environmental sustainability. Find more details in the [Contribution Guide](https://opensustain.tech/contributing/).
=> add flixOpt into ESM frameworks

README.md
Update Climate Modeling -> Earth and Climate Modeling -> SCREAM link to point to updated repo
https://github.com/E3SM-Project/scream ->
https://github.com/E3SM-Project/E3SM/tree/master/components/eamxx
Not a new project, the repo was just moved in December 2024.  see old URL for details.
=> Update SCREAM link in README.md

README.md
[** https://github.com/e3-/resolve ** ]
=> add e3/resolve into ESM frameworks

README.md
https://github.com/ecmwf/WeatherGenerator
=> Add WeatherGenerator

README.md
https://github.com/jmigueldelgado/buhayra-semiarido/
Updating a link as the [current one](https://github.com/jmigueldelgado/buhayra) is not functional. Not sure however the replacement suggested in the PR is the best as the linked project seems to be not very active in the recent years.
2. All new projects listed will be posted on our [Mastodon](https://mastodon.social/@opensustaintech) and …
=> Update url for buhayra tool

README.md
Attempt to fix https://github.com/protontypes/open-sustainable-technology/issues/1175
=> Remove 2nd url from Modbus Schema Toolkit

README.md
https://github.com/Critical-Infrastructure-Systems-Lab/DHALSIM
=> Add DHALSIM
